apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ennote-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ennote-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ennote-agent.fullname" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ennote-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ennote-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ennote-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io